# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: molnmiljo

# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-app

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

custom:
  esbuild:
    minify: true

functions:
  PostTodo:
    handler: functions/PostTodo/index.handler
    events:
      - httpApi:
          path: /todos
          method: post

  GetTodos:
    handler: functions/GetTodos/index.handler
    events:
      - httpApi:
          path: /todos
          method: get

  DeleteTodo:
    handler: functions/DeleteTodo/index.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: delete

  UpdateTodo:
    handler: functions/UpdateTodo/index.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: put

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my-todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST